[TextField] Fix of Uncaught TypeError: r.inputRef.focus is not a function (#13091)
* Fix of Uncaught TypeError: r.inputRef.focus is not a function when clicking on InputAdornment

* simple test proxy function exist

* simple test onFocus is called after proxying

* let's merge